spring:
  application:
    name: bank-account-microservice
  data:
    mongodb:
      uri: mongodb://localhost:27017/bank-account-service-db
      auto-index-creation: true
  webflux:
    base-path: /api/v1/accounts
server:
  port: 7072
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}