spring:
  application:
    name: bank-client-microservice
  data:
    mongodb:
      uri: mongodb://localhost:27017/bank-client-service-db
      auto-index-creation: true
  webflux:
    base-path: /api/v1/clients
server:
  port: 9001
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}