spring:
  application:
    name: bank-client-microservice
  data:
    mongodb:
      uri: mongodb://localhost:27017/bank-client-service-db
      auto-index-creation: true
  webflux:
    base-path: /api/v1
server:
  port: 9001