spring:
  application:
    name: bank-product-microservice
  data:
    mongodb:
      uri: mongodb://localhost:27017/bank-product-service-db
      auto-index-creation: true
  webflux:
    base-path: /api/v1/products
server:
  port: 9003

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}