spring:
  application:
    name: bank-product-microservice
  data:
    mongodb:
      uri: mongodb://localhost:27017/bank-product-service-db
      auto-index-creation: true
  webflux:
    base-path: /api/v1
server:
  port: 9003